### ISSUE TITLE
The focus on HTML generation is misleading

### ISSUE THREAD

**Issue by chocolateboy** [debrouwere/render#1]
This is an excellent tool which does exactly what I want in the way that I want, but I almost ended up not using it (and potentially reinventing it) because it's presented as a tool for generating HTML.

I understand that that might be the most common use case, but there are plenty of others (I'm currently using it for code generation).

Here's a suggestion for the summary:

> Render Jade, Handlebars, Swig and most other kinds of template on the command line. Filename templates mean you can render many files at once and name them however you like.

The intro could be reworded to something like:

> Render is an advanced command-line interface which renders text (e.g. HTML, config files, source code &c.) from Jade templates, Handlebars templates, Swig templates and pretty much any other kind of template you can think of.

**Comment by debrouwere** [comment]
Cool, thanks for this (& the other issues you submitted). I should hopefully have some time in late June to put out a new release.
